######################################################################
# Automatically generated by qmake (3.0) Sun Jan 7 20:11:09 2018
######################################################################

QMAKE_CXX = clang++
QMAKE_LINK = clang++
TEMPLATE = app
CONFIG += console c++14 thread
CONFIG -= qt app_bundle
TARGET = mexfw
INCLUDEPATH += . \
               ./thirdparty/elle/src \
               ./thirdparty/elle/_build/linux64/boost/1.60.0/include \
               ./thirdparty/elle/_build/linux64/openssl/include \
               ./thirdparty/rapidjson/include \
               ./thirdparty/CTPL \

DEFINES += RAPIDJSON_SSE2 RAPIDJSON_NEON 

LIBS += ./thirdparty/elle/_build/linux64/lib/libelle_core.so \
        ./thirdparty/elle/_build/linux64/lib/libelle_reactor.so \
        ./thirdparty/elle/_build/linux64/lib/libelle_protocol.so \
        ./thirdparty/elle/_build/linux64/lib/libelle_cryptography.so \
        ./thirdparty/elle/_build/linux64/lib/libcurl.so.4 \
        ./thirdparty/elle/_build/linux64/lib/libssl.so.1.0.0 \ 
        ./thirdparty/elle/_build/linux64/lib/libcrypto.so.1.0.0 \
        ./thirdparty/elle/_build/linux64/lib/libfuse.so.2
LIBS += ./thirdparty/elle/_build/linux64/lib/libboost_chrono.so.1.60.0 \
        ./thirdparty/elle/_build/linux64/lib/libboost_context.so.1.60.0 \
        ./thirdparty/elle/_build/linux64/lib/libboost_date_time.so.1.60.0 \
        ./thirdparty/elle/_build/linux64/lib/libboost_filesystem.so.1.60.0 \
        ./thirdparty/elle/_build/linux64/lib/libboost_signals.so.1.60.0 \
        ./thirdparty/elle/_build/linux64/lib/libboost_system.so.1.60.0 \
        ./thirdparty/elle/_build/linux64/lib/libboost_thread.so.1.60.0 \
        ./thirdparty/elle/_build/linux64/lib/libboost_timer.so.1.60.0

# Input
HEADERS += *.hpp 

SOURCES += main.cpp 

